name: Deploy PlatformOps

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          cd /home/ubuntu/platformops
          git pull origin main
          docker compose build --no-cache
          docker compose up -d
          docker compose ps
